services:
  mediamtx:
    build:
      context: ./
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: vigil-mediamtx:1.15.6
    env_file: .env
    container_name: vigil-mediamtx
    ports:
      - "8554:8554"
      - "8889:8889"
      - "8189:8189/tcp"
      - "8189:8189/udp" 
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./scripts:/scripts:ro
